language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
sudo: false
script: "npm run-script test-travis && node benchmark/simple_get.js"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
